## 데이터 수집 준비

In [ ]:
#장르별 top 게임 확인

import requests
import pandas as pd

CHARTS_URL = "https://api.steampowered.com/ISteamChartsService/GetMostPlayedGames/v1/"
APPDETAILS_URL = "https://store.steampowered.com/api/appdetails"


#Steam Charts API에서 'Most Played' 상위 게임 목록 가져오기.
#https://api.steampowered.com/ISteamChartsService/GetMostPlayedGames/v1/

def get_top_games_from_charts(max_games=100):

    params = {"count": max_games}
    resp = requests.get(CHARTS_URL, params=params)
    resp.raise_for_status()

    data = resp.json()
    ranks = data.get("response", {}).get("ranks", [])

    rows = []
    for r in ranks[:max_games]:
        rows.append({
            "rank": r.get("rank"),
            "appid": r.get("appid"),
            "peak_in_game": r.get("peak_in_game"),
            "last_week_rank": r.get("last_week_rank"),
        })

    return pd.DataFrame(rows)

In [ ]:

 # appdetails API로부터 게임 이름 + 장르 리스트 가져오기.
 # language='english'로 고정해서 장르가 러시아어(Экшены) 등으로 나오는 문제 방지.
   
def fetch_app_info(appid, language="english"):

    params = {
        "appids": appid,
        "cc": "us",
        "l": language,
    }
    resp = requests.get(APPDETAILS_URL, params=params)
    resp.raise_for_status()

    data = resp.json().get(str(appid), {})
    if not data.get("success"):
        return None, []

    app_data = data.get("data", {})
    name = app_data.get("name", None)
    genres_raw = app_data.get("genres", [])
    genres = [g.get("description", "") for g in genres_raw if g.get("description")]

    return name, genres

In [ ]:

# Charts API에서 상위 max_games 게임 (rank, appid, peak_in_game, last_week_rank) 가져오고
# 각 게임의 이름(name), genres, primary_genre(첫 장르) 붙여서 DataFrame 반환.

def build_genre_dataframe(max_games=100):

    base_df = get_top_games_from_charts(max_games=max_games)

    names = []
    all_genres = []
    primary_genres = []

    for appid in base_df["appid"]:
        name, genres = fetch_app_info(appid, language="english")
        names.append(name)
        all_genres.append(genres)
        primary_genres.append(genres[0] if genres else None)

    base_df["name"] = names
    base_df["genres"] = all_genres
    base_df["primary_genre"] = primary_genres

    return base_df

In [ ]:
# primary_genre(첫 장르) 기준으로, 각 장르별 상위 k개 게임만 남긴 DataFrame 반환.
# rank가 낮을수록 상위.
def top_k_per_genre(df, k=3):
    df = df.dropna(subset=["primary_genre"]).copy()
    df_sorted = df.sort_values("rank")
    top_df = df_sorted.groupby("primary_genre", as_index=False).head(k)
    top_df = top_df.sort_values(["primary_genre", "rank"]).reset_index(drop=True)
    return top_df

In [ ]:
df_all = build_genre_dataframe(max_games=100)
df_all.head()

,rank,appid,peak_in_game,last_week_rank,name,genres,primary_genre
0,1,730,1330302,1,Counter-Strike 2,"[Action, Free To Play]",Action
1,2,570,779783,2,Dota 2,"[Action, Strategy, Free To Play]",Action
2,3,578080,613981,3,PUBG: BATTLEGROUNDS,"[Action, Adventure, Massively Multiplayer, Fre...",Action
3,4,431960,126362,4,Wallpaper Engine,"[Casual, Indie, Animation & Modeling, Design &...",Casual
4,5,1808500,336191,5,ARC Raiders,[Action],Action

In [ ]:
# 장르별로 상위 4개씩만
df_top = top_k_per_genre(df_all, k=4)
df_top[["primary_genre", "rank", "appid", "name"]]

,primary_genre,rank,appid,name
0,Action,1,730,Counter-Strike 2
1,Action,2,570,Dota 2
2,Action,3,578080,PUBG: BATTLEGROUNDS
3,Action,5,1808500,ARC Raiders
4,Adventure,31,1086940,Baldur's Gate 3
5,Adventure,35,438100,VRChat
6,Adventure,49,1222670,The Sims™ 4
7,Audio Production,100,629520,Soundpad
8,Casual,4,431960,Wallpaper Engine
9,Casual,40,3419430,Bongo Cat
10,Casual,55,4000,Garry's Mod
11,Casual,85,2379780,Balatro
12,Indie,17,413150,Stardew Valley
13,Indie,32,227300,Euro Truck Simulator 2
14,Indie,62,244210,Assetto Corsa
15,Indie,72,108600,Project Zomboid
16,RPG,48,1091500,Cyberpunk 2077
17,RPG,56,489830,The Elder Scrolls V: Skyrim Special Edition
18,RPG,92,1158310,Crusader Kings III
19,RPG,96,377160,Fallout 4
20,Racing,42,284160,BeamNG.drive
21,Simulation,25,3405690,EA SPORTS FC™ 26
22,Simulation,27,394360,Hearts of Iron IV
23,Simulation,37,1449850,Yu-Gi-Oh! Master Duel
24,Simulation,50,3224770,Umamusume: Pretty Derby
25,Sports,93,3472040,NBA 2K26
26,Strategy,59,289070,Sid Meier’s Civilization® VI
27,Strategy,78,3450310,Europa Universalis V
28,Strategy,90,960090,Bloons TD 6
29,Strategy,91,813780,Age of Empires II: Definitive Edition
30,Utilities,74,1905180,OBS Studio

## 데이터 수집

In [ ]:
import time
from datetime import datetime, timezone

# 수집할 게임 id
app_ids = [
    730, 570, 578080, 1086940, 438100, 1222670, 431960, 413150, 227300,
    1091500, 489830, 394360, 3405690, 1449850, 289070, 3450310, 813780
]

# 수집 기간: 최근 3년(2023-01-01 ~ 현재)
start_date = datetime(2023, 1, 1, tzinfo=timezone.utc)
end_date = datetime.now(timezone.utc)

def fetch_reviews_for_app(app_id, start_date, end_date, max_pages=200):
    url = f"https://store.steampowered.com/appreviews/{app_id}"
    params = {
        'json': 1,
        'language': 'koreana',
        'filter': 'recent',
        'num_per_page': 100,
        'purchase_type': 'all',
        'day_range': 365 * 3,
        'cursor': '*'
    }

    collected = []
    page = 0
    stop_paging = False

    while not stop_paging and page < max_pages:
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"[경고] app_id {app_id} 요청 실패: {response.status_code}")
            break

        data = response.json()
        reviews = data.get('reviews', [])
        if not reviews:
            break

        for review in reviews:
            text = review.get('review', '').strip()

            # 리뷰 길이 30자 이상만
            if len(text) < 30:
                continue

            ts = review.get('timestamp_created', 0)
            dt = datetime.fromtimestamp(ts, tz=timezone.utc)

            # 날짜 범위 
            if dt < start_date:
                stop_paging = True
                break
            if dt > end_date:
                continue

            author = review.get('author', {})

            collected.append({
                "app_id": app_id,
                "review": text,
                "review_len": len(text),   
                "voted_up": review.get('voted_up', None),
                "playtime_forever": author.get('playtime_forever', 0),
                "playtime_at_review": author.get('playtime_at_review', 0),
                "language": review.get('language', ''),
                "steam_purchase": review.get('steam_purchase', False),
                "timestamp_created": ts,
                "datetime_created_utc": dt
            })

        # 다음 페이지로 이동
        cursor = data.get('cursor')
        if not cursor:
            break

        params['cursor'] = cursor
        page += 1
        time.sleep(0.5)

    print(f"app_id {app_id}: 수집된 리뷰 수 = {len(collected)}")
    return collected


# 전체 수집
all_reviews = []
for app_id in app_ids:
    all_reviews.extend(fetch_reviews_for_app(app_id, start_date, end_date))

df = pd.DataFrame(all_reviews)

print("총 리뷰 수:", len(df))

app_id 730: 수집된 리뷰 수 = 1360
app_id 570: 수집된 리뷰 수 = 160
app_id 578080: 수집된 리뷰 수 = 2696
app_id 1086940: 수집된 리뷰 수 = 5679
app_id 438100: 수집된 리뷰 수 = 573
app_id 1222670: 수집된 리뷰 수 = 443
app_id 431960: 수집된 리뷰 수 = 567
app_id 413150: 수집된 리뷰 수 = 3171
app_id 227300: 수집된 리뷰 수 = 877
app_id 1091500: 수집된 리뷰 수 = 3693
app_id 489830: 수집된 리뷰 수 = 497
app_id 394360: 수집된 리뷰 수 = 771
app_id 3405690: 수집된 리뷰 수 = 111
app_id 1449850: 수집된 리뷰 수 = 987
app_id 289070: 수집된 리뷰 수 = 1035
app_id 3450310: 수집된 리뷰 수 = 178
app_id 813780: 수집된 리뷰 수 = 242
총 리뷰 수: 23040

In [ ]:
df.head(10)

,app_id,review,review_len,voted_up,playtime_forever,playtime_at_review,language,steam_purchase,timestamp_created,datetime_created_utc
0,730,FPS를 좋아하는 사람이라면 한 번쯤은 꼭 해봐야 하는 FPS근본겜. 과거부터 현재...,64,True,194,194,koreana,False,1763876321,2025-11-23 05:38:41+00:00
1,730,과금 요소도 없고 초보자도무난히즐길수있으며 자신의 실력과 비슷한 팀원과 플레이 가능함 ㅋ,49,True,1329,1282,koreana,False,1763817657,2025-11-22 13:20:57+00:00
2,730,핵 짱깨 새끼들 핵 사이트 링크 보내는거 빼고 다 좋습니다,32,True,7690,7208,koreana,False,1763739047,2025-11-21 15:30:47+00:00
3,730,⣿⣿⣿⣿⣿⠟⠋⠄⠄⠄⠄⠄⠄⠄⢁⠈⢻⢿⣿⣿⣿⣿⣿⣿\r\n⣿⣿⣿⣿⣿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈...,336,True,3629,2985,koreana,False,1763711259,2025-11-21 07:47:39+00:00
4,730,ㅈ같은 짜장새ㅡㅡ끼들 지역락좀 걸어라 씨1발\r\n⣿⣿⣿⣿⣿⠟⠋⠄⠄⠄⠄⠄⠄⠄⢁⠈⢻⢿...,362,True,2150,2150,koreana,False,1763561892,2025-11-19 14:18:12+00:00
5,730,it's very good more than other fps games my fa...,52,True,39461,36581,koreana,True,1763476970,2025-11-18 14:42:50+00:00
6,730,나는 이게임이 왜 재미있다고 하는지 모르겠네. 왜 맨날 1위지?,35,False,1032,787,koreana,True,1763424392,2025-11-18 00:06:32+00:00
7,730,"재밌음 , ㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱ...",54,True,3096,3077,koreana,False,1763397051,2025-11-17 16:30:51+00:00
8,730,이미 카스 에선 중국 무비자 입국 체험판을 즐기실수 있습니다,33,True,11860,10598,koreana,True,1763363133,2025-11-17 07:05:33+00:00
9,730,클래식 고전의 최고봉 못해도 재밌고 잘해지면 더 재밌음,30,True,1528,1419,koreana,True,1763306880,2025-11-16 15:28:00+00:00

In [ ]:
df.to_csv('game_review_raw.csv')

## 데이터 전처리

In [ ]:
import re

def clean_text(t: str) -> str:
    # 1) 기본 특수문자 정리
    t = re.sub(r"\s+", " ", t)                 # 중복 공백 제거
    t = re.sub(r"[^\w\s가-힣.,!?]", "", t)     # 이모티콘/특수문자 제거
    t = t.strip()
    return t

def normalize_repeats(t: str) -> str:
    # 2) 같은 글자가 3번 이상 반복 → 2번으로 줄임 (예: ㅋㅋㅋㅋ → ㅋㅋ, ㄱㄱㄱㄱㄱ → ㄱㄱ)
    t = re.sub(r"(.)\1{2,}", r"\1\1", t)
    return t

def preprocess_reviews(df: pd.DataFrame,
                       min_len: int = 20,
                       max_len: int = 1500) -> pd.DataFrame:
    
    df = df.copy()

    # 원본 review가 NaN인 건 일단 빈 문자열로 처리
    df['clean_review'] = df['review'].fillna('').astype(str)

    # 1) 기본 클렌징 + 2) 반복 축약
    df['clean_review'] = (
        df['clean_review']
        .apply(clean_text)
        .apply(normalize_repeats)
    )

    # 3) 완전히 비어 있는 문자열 제거
    df['clean_review'] = df['clean_review'].str.strip()
    df = df[df['clean_review'] != '']

    # 4) 최소 길이 필터 (예: 30자 미만 제거)
    df = df[df['clean_review'].str.len() >= min_len]

    # 5) 한글이 하나도 없는 리뷰 제거 (영어-only 등)
    has_korean = df['clean_review'].str.contains(r"[가-힣]")
    df = df[has_korean]

    # 6) 너무 긴 리뷰는 max_len에서 잘라주기 (모델 입력 길이 관리용)
    if max_len is not None:
        df['clean_review'] = df['clean_review'].str.slice(0, max_len)

    # 인덱스 정리
    df = df.reset_index(drop=True)
    return df

In [ ]:
df_clean = preprocess_reviews(df)

In [ ]:
df_clean.to_csv('game_review_clean.csv')

In [ ]:
import kss

#문장단위로 나누기
sent_rows = []

for idx, row in df_clean.iterrows():
    text = row["clean_review"]
    app_id = row["app_id"]
    genre = row.get("primary_genre", None)  # 있으면 같이 들고가고

    sentences = kss.split_sentences(text)
    for s in sentences:
        s = s.strip()
        if len(s) < 10:  # 너무 짧은 문장 제외
            continue
        sent_rows.append({
            "app_id": app_id,
            "primary_genre": genre,
            "sentence": s
        })

df_sent = pd.DataFrame(sent_rows)

[Kss]: Because there's no supported C++ morpheme analyzer, Kss will take pecab as a backend. :D
For your information, Kss also supports mecab backend.
We recommend you to install mecab or konlpy.tag.Mecab for faster execution of Kss.
Please refer to following web sites for details:
- mecab: https://github.com/hyunwoongko/python-mecab-kor
- konlpy.tag.Mecab: https://konlpy.org/en/latest/api/konlpy.tag/#mecab-class

/Users/eunyeongkim/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pecab/_tokenizer.py:265: RuntimeWarning: overflow encountered in scalar add
  from_pos_data.costs[idx]
/Users/eunyeongkim/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pecab/_tokenizer.py:274: RuntimeWarning: overflow encountered in scalar add
  least_cost += word_cost

In [ ]:
df_sent.to_csv('game_review_sentence.csv')

## TF-IDF & 계층트리

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np
import pandas as pd

texts = df_clean["clean_review"].tolist()

# 1) 문서 빈도 계산
cv = CountVectorizer(
    min_df=5,
    token_pattern=r'(?u)\b[가-힣A-Za-z]{2,}\b'
)
X = cv.fit_transform(texts)
vocab = cv.get_feature_names_out()
doc_freq = X.astype(bool).sum(axis=0).A1
N_docs = X.shape[0]

df_stats = pd.DataFrame({
    "token": vocab,
    "doc_freq": doc_freq,
    "doc_ratio": doc_freq / N_docs
}).sort_values("doc_ratio", ascending=False)

# 2) 자동 불용어
auto_stop = df_stats.loc[df_stats["doc_ratio"] > 0.3, "token"].tolist()

# 3) 수동 불용어
manual_stop = ["게임", "게임을", "게임이", "게임은", "플레이", "하는", "했다", "있다"]

# ★ set → list로 변환해야 함
stopwords = list(set(auto_stop + manual_stop))

# 4) TF-IDF 벡터라이저
tfidf = TfidfVectorizer(
    max_features=2000,
    min_df=5,
    max_df=0.8,
    stop_words=stopwords,
    token_pattern=r'(?u)\b[가-힣A-Za-z]{2,}\b',
    ngram_range=(1, 2)
)

tfidf_mat = tfidf.fit_transform(texts)
feature_names = tfidf.get_feature_names_out()
scores = tfidf_mat.sum(axis=0).A1

keywords_df = pd.DataFrame({
    "keyword": feature_names,
    "score": scores
}).sort_values("score", ascending=False)

In [ ]:
from kiwipiepy import Kiwi
kiwi = Kiwi()

def tokenize_noun_adj(text):
    tokens = []
    for word, tag, _, _ in kiwi.tokenize(text):
        if tag.startswith("NN") or tag.startswith("VA"):  # 명사, 형용사
            if len(word) >= 2:
                tokens.append(word)
    return tokens

tfidf = TfidfVectorizer(
    tokenizer=tokenize_noun_adj,
    lowercase=False,
    min_df=5,
    max_df=0.8,
    max_features=2000
)
tfidf_mat = tfidf.fit_transform(texts)

/Users/eunyeongkim/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [ ]:
feature_names = tfidf.get_feature_names_out()
scores = tfidf_mat.sum(axis=0).A1  # 각 단어의 TF-IDF 총합

keywords_df = pd.DataFrame({
    "keyword": feature_names,
    "score": scores
}).sort_values("score", ascending=False).reset_index(drop=True)

keywords_df.head(50)

   keyword        score
0       게임  2023.920604
1       재밌  1039.126327
2       시간   914.953147
3      플레이   517.938471
4       사람   436.140494
5      재미있   429.726030
6       버그   423.021514
7       생각   403.092106
8       추천   384.748791
9       재미   376.521632
10      모드   373.783298
11     스토리   365.066135
12      정도   320.158509
13      친구   316.189170
14      처음   311.290530
15      인생   305.474269
16      시작   302.180389
17      최고   262.343802
18      엔딩   244.805683
19      힐링   239.279249
20      그렇   225.202017
21      갓겜   216.883765
22      느낌   206.199269
23      구매   199.252722
24      어렵   196.512661
25      이상   190.733388
26      한글   189.736262
27      회차   188.650322
28      전투   173.918224
29      할인   170.671456
30    업데이트   168.959146
31      때문   164.781506
32      몰입   164.106034
33      진행   163.665748
34      유저   162.149158
35      패치   157.178049
36      화면   155.901403
37      가능   155.700996
38      자체   147.727901
39     캐릭터   146.877697
40     그래픽   145.590372
41      단점   144.475467
42      다양   140.401062
43      아쉽   139.470582
44      배경   138.547836
45      힘들   137.839387
46      문명   135.805333
47      출시   134.682621
48      동안   133.743750
49      스팀   133.478106

### 계층트리 검증

In [ ]:
#계층트리 초안(최종본과 다름. 검증용 코드 실행을 위해 남겨둠)

SUB_TO_TOP = {
    # GAMEPLAY
    "GP_CONTROL": "GAMEPLAY",
    "GP_COMBAT": "GAMEPLAY",
    "GP_CONTENT": "GAMEPLAY",
    "GP_FUN": "GAMEPLAY",

    # AUDIOVISUAL
    "AV_GRAPHICS": "AUDIOVISUAL",
    "AV_SOUND": "AUDIOVISUAL",
    "AV_UI_FEEL": "AUDIOVISUAL",

    # TECHNICAL
    "TECH_PERFORMANCE": "TECHNICAL",
    "TECH_BUG": "TECHNICAL",
    "TECH_NET": "TECHNICAL",
    "TECH_ANTICHEAT": "TECHNICAL",
    "TECH_LOCALIZATION": "TECHNICAL",

    # SYSTEM_BALANCE
    "SYS_RULE": "SYSTEM_BALANCE",
    "SYS_BALANCE": "SYSTEM_BALANCE",
    "SYS_AI": "SYSTEM_BALANCE",

    # ECONOMY_PROGRESSION
    "ECO_MONETIZATION": "ECONOMY_PROGRESSION",
    "ECO_REWARD": "ECONOMY_PROGRESSION",
    "ECO_PROGRESSION": "ECONOMY_PROGRESSION",

    # MULTI / COMMUNITY
    "MULTI_MATCHING": "MULTI_COMMUNITY",
    "MULTI_FAIRNESS": "MULTI_COMMUNITY",
    "COMMUNITY_BEHAVIOR": "MULTI_COMMUNITY",

    # OTHER
    "OTHER": "OTHER",
}

SUB_SEEDS = {
    # --- GAMEPLAY ---
    # 조작계
    "GP_CONTROL": [
    "조작", "컨트롤", "조종", "키감", "반응성",
    "키보드", "마우스", "패드", "운전", "조작감"
],

"GP_COMBAT": [
    "전투", "타격감", "싸움", "전쟁", "보스전",
    "콤보", "딜링", "무기", "근접전", "전투력"
],

"GP_CONTENT": [
    "스토리", "엔딩", "세계", "세계관", "맵", "모드", 
    "챕터", "퀘스트", "콘텐츠", "컨텐츠", "캐릭터",
    "농사", "볼륨", "자유도", "선택지", "분기",
    "대화", "이야기", "제작", "건설", "진행도"
],

"GP_FUN": [
    "재밌", "재미", "재미있", "꿀잼", "힐링", "중독",
    "중독성", "몰입", "몰입도", "명작", "갓겜",
    "최고", "인생", "취향", "감동", "재밌다",
    "재미있다", "스트레스해소", "즐거움"
],


 # --- AUDIOVISUAL ---
"AV_GRAPHICS": [
    "그래픽", "화면", "배경", "색감", "아트", "모델링",
    "디테일", "연출", "감성", "분위기", "라이팅",
    "텍스처", "시각효과", "카메라워크", "외형", "스킨"
],

"AV_SOUND": [
    "사운드", "음악", "bgm", "효과음", "성우", "보이스",
    "OST", "음향", "노래"
],

"AV_UI_FEEL": [
    "ui", "ux", "인터페이스", "메뉴", "가독성", "시인성",
    "편의성", "안내", "버튼"
],

# --- TECHNICAL ---
"TECH_BUG": [
    "버그", "오류", "튕김", "글리치", "에러", "버벅",
    "오작동", "문제", "깨짐"
],

"TECH_PERFORMANCE": [
    "프레임", "드랍", "프레임드랍", "최적화", "렉", 
    "로딩", "로딩속도", "지연", "발열", "성능",
    "프레임문제", "버벅임", "업데이트", "패치"
],

"TECH_NET": [
    "서버", "핑", "매칭서버", "접속", "로그인",
    "네트워크", "지연", "끊김"
],

"TECH_ANTICHEAT": [
    "핵", "치터", "핵쟁이", "감사", "안티치트", 
    "핵유저", "핵문제"
],

"TECH_LOCALIZATION": [
    "한글", "한글화", "자막", "번역", "현지화",
    "오역", "언어지원"
],

# --- SYSTEM / BALANCE ---
"SYS_RULE": [
    "룰", "규칙", "시스템", "튜토리얼", "가이드",
    "설명", "메커니즘", "메뉴얼"
],

"SYS_BALANCE": [
    "밸런스", "op", "너프", "상향", "하향", "메타",
    "난이도", "어렵", "진입장벽", "장벽", "도전",
    "불합리", "불공정"
],

"SYS_AI": [
    "ai", "인공지능", "봇", "ai난이도", "적 ai",
],

# --- ECONOMY / PROGRESSION ---
"ECO_MONETIZATION": [
    "과금", "현질", "유료", "무료", "구매", "가격", 
    "할인", "dlc", "유료dlc", "패스", "배틀패스", 
    "스킨", "코스튬", "재화"
],

"ECO_REWARD": [
    "보상", "드랍", "파밍", "경험치", "골드", "전리품",
    "획득", "보상률"
],

"ECO_PROGRESSION": [
    "레벨", "성장", "진행도", "육성", "숙련도",
    "업그레이드", "강화", "진행속도"
],

# --- MULTI / COMMUNITY ---
"MULTI_MATCHING": [
    "매칭", "큐", "큐잡", "티어", "랭크", 
    "매칭속도", "mmr"
],

"MULTI_FAIRNESS": [
    "트롤", "고인물", "불공정", "언밸런스",
    "핵쟁이", "문제유저"
],

"COMMUNITY_BEHAVIOR": [
    "유저", "사람", "친구", "채팅", "독성", 
    "매너", "욕설", "커뮤니티", "소통"
],

"OTHER": [
    "게임", "플레이", "스팀", "작품"
]
}

def map_keyword_to_aspect(keyword: str):
    """
    TF-IDF로 뽑힌 한 단어(keyword)를
    가장 관련성 높은 sub_aspect / top_aspect로 매핑.
    단순 substring 기반 rule 매칭.
    """
    keyword = keyword.lower()

    # 우선순위: 여러 sub_aspect에 걸리는 경우,
    # *가장 길이가 긴 seed*를 포함하는 쪽으로 선택 (좀 더 구체적인 것 우선)
    candidates = []
    for sub, seeds in SUB_SEEDS.items():
        for seed in seeds:
            if seed.lower() in keyword:
                candidates.append((sub, seed))

    if not candidates:
        return {
            "top_aspect": "UNMAPPED",
            "sub_aspect": "UNMAPPED",
            "match_seed": None,
        }

    # 길이가 긴 seed를 우선 (좀 더 구체적인 매칭)
    candidates.sort(key=lambda x: len(x[1]), reverse=True)
    best_sub, best_seed = candidates[0]
    top = SUB_TO_TOP.get(best_sub, "OTHER")

    return {
        "top_aspect": top,
        "sub_aspect": best_sub,
        "match_seed": best_seed,
    }

In [ ]:
# 상위 N개 키워드만 계층트리 검증에 사용 (예: 200개)
N = 200
df_kw = keywords_df.head(N).copy()

mapped_top = []
mapped_sub = []
matched_seed = []

for kw in df_kw["keyword"]:
    res = map_keyword_to_aspect(kw)
    mapped_top.append(res["top_aspect"])
    mapped_sub.append(res["sub_aspect"])
    matched_seed.append(res["match_seed"])

df_kw["mapped_top"] = mapped_top
df_kw["mapped_sub"] = mapped_sub
df_kw["match_seed"] = matched_seed

df_kw.head(20)

   keyword        score       mapped_top          mapped_sub match_seed
0       게임  2023.920604            OTHER               OTHER         게임
1       재밌  1039.126327         GAMEPLAY              GP_FUN         재밌
2       시간   914.953147         UNMAPPED            UNMAPPED       None
3      플레이   517.938471            OTHER               OTHER        플레이
4       사람   436.140494  MULTI_COMMUNITY  COMMUNITY_BEHAVIOR         사람
5      재미있   429.726030         GAMEPLAY              GP_FUN        재미있
6       버그   423.021514        TECHNICAL            TECH_BUG         버그
7       생각   403.092106         UNMAPPED            UNMAPPED       None
8       추천   384.748791         UNMAPPED            UNMAPPED       None
9       재미   376.521632         GAMEPLAY              GP_FUN         재미
10      모드   373.783298         GAMEPLAY          GP_CONTENT         모드
11     스토리   365.066135         GAMEPLAY          GP_CONTENT        스토리
12      정도   320.158509         UNMAPPED            UNMAPPED       None
13      친구   316.189170  MULTI_COMMUNITY  COMMUNITY_BEHAVIOR         친구
14      처음   311.290530         UNMAPPED            UNMAPPED       None
15      인생   305.474269         GAMEPLAY              GP_FUN         인생
16      시작   302.180389         UNMAPPED            UNMAPPED       None
17      최고   262.343802         GAMEPLAY              GP_FUN         최고
18      엔딩   244.805683         GAMEPLAY          GP_CONTENT         엔딩
19      힐링   239.279249         GAMEPLAY              GP_FUN         힐링

In [ ]:
aspect_counts = (
    df_kw[df_kw["mapped_sub"] != "UNMAPPED"]
    .groupby(["mapped_top", "mapped_sub"])
    .size()
    .reset_index(name="n_keywords")
    .sort_values(["mapped_top", "n_keywords"], ascending=[True, False])
)

aspect_counts

             mapped_top          mapped_sub  n_keywords
0           AUDIOVISUAL         AV_GRAPHICS           4
1   ECONOMY_PROGRESSION    ECO_MONETIZATION           4
3              GAMEPLAY          GP_CONTENT          13
5              GAMEPLAY              GP_FUN          12
2              GAMEPLAY           GP_COMBAT           1
4              GAMEPLAY          GP_CONTROL           1
6       MULTI_COMMUNITY  COMMUNITY_BEHAVIOR           3
7                 OTHER               OTHER           4
8        SYSTEM_BALANCE         SYS_BALANCE           3
9        SYSTEM_BALANCE            SYS_RULE           1
11            TECHNICAL            TECH_BUG           3
14            TECHNICAL    TECH_PERFORMANCE           3
10            TECHNICAL      TECH_ANTICHEAT           1
12            TECHNICAL   TECH_LOCALIZATION           1
13            TECHNICAL            TECH_NET           1

In [ ]:
unmapped = df_kw[df_kw["mapped_sub"] == "UNMAPPED"].copy()
unmapped.head(50)

    keyword       score mapped_top mapped_sub match_seed
2        시간  914.953147   UNMAPPED   UNMAPPED       None
7        생각  403.092106   UNMAPPED   UNMAPPED       None
8        추천  384.748791   UNMAPPED   UNMAPPED       None
12       정도  320.158509   UNMAPPED   UNMAPPED       None
14       처음  311.290530   UNMAPPED   UNMAPPED       None
16       시작  302.180389   UNMAPPED   UNMAPPED       None
20       그렇  225.202017   UNMAPPED   UNMAPPED       None
22       느낌  206.199269   UNMAPPED   UNMAPPED       None
25       이상  190.733388   UNMAPPED   UNMAPPED       None
27       회차  188.650322   UNMAPPED   UNMAPPED       None
31       때문  164.781506   UNMAPPED   UNMAPPED       None
33       진행  163.665748   UNMAPPED   UNMAPPED       None
37       가능  155.700996   UNMAPPED   UNMAPPED       None
38       자체  147.727901   UNMAPPED   UNMAPPED       None
41       단점  144.475467   UNMAPPED   UNMAPPED       None
42       다양  140.401062   UNMAPPED   UNMAPPED       None
43       아쉽  139.470582   UNMAPPED   UNMAPPED       None
45       힘들  137.839387   UNMAPPED   UNMAPPED       None
46       문명  135.805333   UNMAPPED   UNMAPPED       None
47       출시  134.682621   UNMAPPED   UNMAPPED       None
48       동안  133.743750   UNMAPPED   UNMAPPED       None
50       새끼  129.992314   UNMAPPED   UNMAPPED       None
51       필요  129.545466   UNMAPPED   UNMAPPED       None
52       이렇  129.080289   UNMAPPED   UNMAPPED       None
54       선택  127.573941   UNMAPPED   UNMAPPED       None
55       아깝  127.226871   UNMAPPED   UNMAPPED       None
56       지금  125.902407   UNMAPPED   UNMAPPED       None
58       하루  120.738501   UNMAPPED   UNMAPPED       None
61  발더스 게이트  116.593455   UNMAPPED   UNMAPPED       None
62       새롭  116.161627   UNMAPPED   UNMAPPED       None
63       어떻  114.341938   UNMAPPED   UNMAPPED       None
64       이후  113.368733   UNMAPPED   UNMAPPED       None
65       이유  112.296475   UNMAPPED   UNMAPPED       None
66       병신  112.142580   UNMAPPED   UNMAPPED       None
68      중국인  111.572458   UNMAPPED   UNMAPPED       None
69       시발  110.985324   UNMAPPED   UNMAPPED       None
70       장점  109.591840   UNMAPPED   UNMAPPED       None
71       카드  108.030837   UNMAPPED   UNMAPPED       None
72       초반  107.814369   UNMAPPED   UNMAPPED       None
73       턴제  107.095639   UNMAPPED   UNMAPPED       None
74       멀티  105.436265   UNMAPPED   UNMAPPED       None
75       평가  105.131288   UNMAPPED   UNMAPPED       None
76      컴퓨터  104.814839   UNMAPPED   UNMAPPED       None
77       장르  104.745560   UNMAPPED   UNMAPPED       None
79       현실  104.225137   UNMAPPED   UNMAPPED       None
83       부분  101.119845   UNMAPPED   UNMAPPED       None
84       다르  100.853584   UNMAPPED   UNMAPPED       None
85       정신  100.493970   UNMAPPED   UNMAPPED       None
86       정지   99.880274   UNMAPPED   UNMAPPED       None
87       즐겁   99.793359   UNMAPPED   UNMAPPED       None

In [ ]:
df_kw.sort_values("score", ascending=False).to_csv('kw_mapping.csv')

## 라벨링

In [9]:
# open ai api key : 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

### 샘플링

In [25]:
import numpy as np

def proportional_sample_by_app(
    df: pd.DataFrame,
    total_n: int = 12000,     # 최종적으로 라벨링할 전체 문장 수
    group_col: str = "app_id",
    random_state: int = 42,
    min_per_group: int = 200  # 각 게임당 최소 보장 문장 수
):
    """
    앱별 문장 수 비율에 비례해서 문장을 뽑되,
    각 app_id별로 최소 min_per_group개는 확보하려는 층화 비례 표본추출 함수.
    """
    # 그룹별 문장 수
    group_counts = df[group_col].value_counts()
    total = group_counts.sum()

    # 비율
    ratios = group_counts / total

    # 비례할당 목표 수
    targets = (ratios * total_n).round().astype(int)

    # 최소 1개 이상, 실제 개수 이내로
    targets = targets.clip(lower=1)
    targets = np.minimum(targets, group_counts)

    # 각 그룹별 최소 min_per_group 확보 (단, 실제 개수보다 크지는 않게)
    targets = np.maximum(targets, np.minimum(min_per_group, group_counts))

    sampled_list = []
    for app_id, n_sample in targets.items():
        df_app = df[df[group_col] == app_id]
        sampled = df_app.sample(n=n_sample, random_state=random_state)
        sampled_list.append(sampled)

    df_sampled = pd.concat(sampled_list).reset_index(drop=True)
    return df_sampled, targets

In [26]:
df_sent_sampled, sample_targets = proportional_sample_by_app(
    df_sent,
    total_n=12000,      # 전체 6만 중 1.2만 정도만 라벨링하자
    group_col="app_id",
    min_per_group=200   # 각 게임당 최소 200문장 확보
)

print("원본 문장 수:", len(df_sent))
print("샘플 문장 수:", len(df_sent_sampled))
sample_targets

원본 문장 수: 60361
샘플 문장 수: 12403

app_id
1086940    3349
1091500    2371
413150     1470
578080     1062
1449850     533
289070      498
730         478
227300      389
438100      349
394360      346
489830      269
431960      246
1222670     243
3450310     200
813780      200
570         200
3405690     200
Name: count, dtype: int64

In [ ]:
len(df_sent_sampled)

12403

### 최종 계층 트리 및 라벨링

In [ ]:
#aspect 일부 수정
TOP_ASPECTS = {
    "GAMEPLAY": "조작감, 전투, 콘텐츠, 재미, 난이도 등 실제 플레이 경험 전반.",
    "AUDIOVISUAL": "그래픽, 아트 스타일, 사운드, 연출 등 시청각 요소.",
    "TECHNICAL": "프레임, 최적화, 버그, 튕김, 서버/핑 등 기술적 안정성과 성능.",
    "SYSTEM_BALANCE": "게임의 규칙/시스템 구조, 밸런스, 메타, AI, 튜토리얼 완성도.",
    "ECONOMY_PROGRESSION": "가격, 과금 정책, P2W, 보상 구조, 성장 속도, 파밍 효율.",
    "MULTI_COMMUNITY": "멀티 매칭, 팀원/상대, 핵/트롤, 유저 매너/독성.",
    "OTHER": "위 분류로 담기 어렵거나 일반적인 감상/사실 서술."
}

SUB_ASPECTS = {
    # GAMEPLAY
    "GP_CONTROL": "조작감, 반응성, 키감.",
    "GP_COMBAT": "전투, 타격감, 전투 시스템.",
    "GP_CONTENT": "콘텐츠 볼륨, 맵/모드 다양성.",
    "GP_FUN": "재미, 몰입감, 플레이 만족도.",

    # AUDIOVISUAL
    "AV_GRAPHICS": "그래픽 품질, 아트, 모델링.",
    "AV_SOUND": "음악, 효과음, 성우.",
    "AV_UI_FEEL": "UI 디자인, 인터페이스 시각 피드백.",

    # TECHNICAL
    "TECH_PERFORMANCE": "프레임, 로딩, 최적화.",
    "TECH_BUG": "버그, 오류, 튕김.",
    "TECH_NET": "서버, 랙, 핑.",
    "TECH_ANTICHEAT": "핵/치터, 안티치트.",
    "TECH_LOCALIZATION": "한글화, 번역 품질, 자막, 언어 지원.",

    # SYSTEM_BALANCE
    "SYS_RULE": "게임 룰, 시스템 구조, 튜토리얼.",
    "SYS_BALANCE": "밸런스, 메타, OP 요소.",
    "SYS_AI": "AI 난이도/행동.",

    # ECONOMY_PROGRESSION
    "ECO_MONETIZATION": "과금, 가격, DLC, P2W.",
    "ECO_REWARD": "보상 구조, 파밍 대비 효율.",
    "ECO_PROGRESSION": "성장 속도, 레벨업, 육성 체감.",

    # MULTI/COMMUNITY
    "MULTI_MATCHING": "매칭 속도/품질, 티어 매칭.",
    "MULTI_FAIRNESS": "트롤, 핵쟁이, 불공정성.",
    "COMMUNITY_BEHAVIOR": "유저 매너, 독성, 채팅 문화."
}

In [ ]:
import json
import time
from openai import OpenAI

client = OpenAI(api_key="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")

In [ ]:
def annotate_sentences_batch_fn(sentences, max_retry=3, debug=False):
    """배치 단위 문장 라벨링 - 최종 버전"""
    
    if not sentences:
        return []
    
    top_aspects_str = "\n".join([f"- {k}: {v}" for k, v in TOP_ASPECTS.items()])
    sub_aspects_str = "\n".join([f"- {k}: {v}" for k, v in SUB_ASPECTS.items()])
    
    sentences_text = "\n".join([f"[{i+1}] {s}" for i, s in enumerate(sentences)])
    
    prompt = f"""
너는 한국어 게임 리뷰 문장을 분석하는 전문 어노테이터야.
각 문장마다 top_aspect, sub_aspect, sentiment를 정확히 하나씩 결정해야 한다.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[1단계] top_aspect 선택 (7개 중 1개)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. GAMEPLAY - 게임 플레이 경험 자체
   핵심 키워드: 재밌다, 재미, 갓겜, 명작, 인생게임, 중독, 개꿀잼, 노잼, 지루함,
               스토리, 엔딩, 세계관, 전투, 전략, 조작, 콘텐츠, 볼륨, 회차

2. TECHNICAL - 기술적 문제/성능
   핵심 키워드: 버그, 튕김, 렉, 프레임, 끊김, 최적화, 오류, 크래시,
               한글, 번역, 한패, 자막, 서버, 핑, 핵방지

3. AUDIOVISUAL - 시청각적 요소
   핵심 키워드: 그래픽, 화질, 비주얼, 그림체, 분위기,
               음악, 사운드, BGM, 더빙, 목소리, UI, 연출

4. SYSTEM_BALANCE - 게임 시스템 설계
   핵심 키워드: 밸런스, 난이도, 쉽다, 어렵다, 빌드, 메타, 조합,
               AI, NPC, 규칙, 시스템 구조

5. ECONOMY_PROGRESSION - 경제/성장 구조
   핵심 키워드: 가격, 할인, 세일, 과금, 현질, DLC, 확장팩,
               보상, 파밍, 성장, 레벨링

6. MULTI_COMMUNITY - 멀티플레이/커뮤니티
   핵심 키워드: 멀티, 협동, 코옵, 매칭, 큐, 핵, 핵쟁이, 치트,
               트롤, 유저, 커뮤니티, 소통

7. OTHER - 게임의 6개 측면을 평가하지 않는 경우
   
   ✅ OTHER 사용 경우:
   • 개인 상황: "게임 덜 했어요", "와이프가 뭐래요", "X시간 플레이함"
   • 메타 발언: "후기 씁니다", "스포 방지", "리뷰 작성"
   • 의미 없음: "ㅋㅋㅋ", "...", "뭐라 말해야할지"
   • 구체적 평가 없는 언급: "개발사 대단", "GOTY감" (측면 명시 없이)
   
   ❌ OTHER 아닌 경우 (흔한 실수!):
   • "재밌다" / "갓겜" / "명작" → GAMEPLAY/GP_FUN
   • "100시간인데 안 질림" → GAMEPLAY/GP_FUN (재미 평가)
   • "버그" 언급 → TECHNICAL/TECH_BUG
   • "한글" 언급 → TECHNICAL/TECH_LOCALIZATION

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[2단계] sub_aspect 선택 (top에 맞는 하위만!)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ 중요: top_aspect가 GAMEPLAY면 sub는 반드시 GP_로 시작!

GAMEPLAY → GP_FUN, GP_CONTENT, GP_COMBAT, GP_CONTROL
  • GP_FUN: 재미, 몰입, 중독성, 전반적 평가
  • GP_CONTENT: 스토리, 엔딩, 콘텐츠양, 볼륨, 회차
  • GP_COMBAT: 전투, 전략, 전투 메커니즘
  • GP_CONTROL: 조작감, 컨트롤, 손맛

TECHNICAL → TECH_BUG, TECH_PERFORMANCE, TECH_LOCALIZATION, TECH_NET, TECH_ANTICHEAT
  • TECH_BUG: 버그, 튕김, 오류, 크래시
  • TECH_PERFORMANCE: 최적화, 프레임, 렉, 로딩
  • TECH_LOCALIZATION: 한글화, 번역, 자막
  • TECH_NET: 서버, 핑, 네트워크
  • TECH_ANTICHEAT: 핵 감지, 치트 방지

AUDIOVISUAL → AV_GRAPHICS, AV_SOUND, AV_UI_FEEL
  • AV_GRAPHICS: 그래픽, 화질, 비주얼
  • AV_SOUND: 사운드, 음악, BGM, 더빙
  • AV_UI_FEEL: UI, UX, 분위기, 연출

SYSTEM_BALANCE → SYS_BALANCE, SYS_DIFFICULTY, SYS_RULE, SYS_AI
  • SYS_BALANCE: 밸런스, 메타, 빌드
  • SYS_DIFFICULTY: 난이도
  • SYS_RULE: 게임 규칙, 시스템
  • SYS_AI: AI, NPC 행동

ECONOMY_PROGRESSION → ECO_MONETIZATION, ECO_REWARD, ECO_PROGRESSION
  • ECO_MONETIZATION: 가격, 과금, DLC, 확장팩
  • ECO_REWARD: 보상, 파밍, 성장속도
  • ECO_PROGRESSION: 레벨링, 진행 구조

MULTI_COMMUNITY → MULTI_MATCHING, MULTI_FAIRNESS, MULTI_SOCIAL, COMMUNITY_BEHAVIOR
  • MULTI_MATCHING: 매칭, 큐
  • MULTI_FAIRNESS: 핵, 치트
  • MULTI_SOCIAL: 협동, 소통
  • COMMUNITY_BEHAVIOR: 유저 매너, 트롤

OTHER → OTHER

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[3단계] sentiment 선택
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

- positive: 칭찬, 만족, 추천, 좋은 평가
- negative: 불만, 비판, 실망, 나쁜 평가
- neutral: 정보 전달, 사실 나열, 애매한 평가

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
필수 예시 (OTHER 구분 명확화)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[재밌다/갓겜 → GAMEPLAY]
"진짜 개꿀잼" → {{"top_aspect":"GAMEPLAY","sub_aspect":"GP_FUN","sentiment":"positive"}}
"갓겜 인정" → {{"top_aspect":"GAMEPLAY","sub_aspect":"GP_FUN","sentiment":"positive"}}
"인생게임이다" → {{"top_aspect":"GAMEPLAY","sub_aspect":"GP_FUN","sentiment":"positive"}}
"100시간 했는데 안 질림" → {{"top_aspect":"GAMEPLAY","sub_aspect":"GP_FUN","sentiment":"positive"}}

[버그/한글 → TECHNICAL]
"버그 너무 많음" → {{"top_aspect":"TECHNICAL","sub_aspect":"TECH_BUG","sentiment":"negative"}}
"한글 패치 ㄱㄱ" → {{"top_aspect":"TECHNICAL","sub_aspect":"TECH_LOCALIZATION","sentiment":"negative"}}

[스토리/콘텐츠 → GAMEPLAY/GP_CONTENT]
"스토리 감동적" → {{"top_aspect":"GAMEPLAY","sub_aspect":"GP_CONTENT","sentiment":"positive"}}
"엔딩이 별로" → {{"top_aspect":"GAMEPLAY","sub_aspect":"GP_CONTENT","sentiment":"negative"}}

[OTHER 올바른 사용]
"게임 아직 덜 했어요" → {{"top_aspect":"OTHER","sub_aspect":"OTHER","sentiment":"neutral"}}
"와이프가 게임 그만하래요" → {{"top_aspect":"OTHER","sub_aspect":"OTHER","sentiment":"neutral"}}
"리뷰 작성합니다" → {{"top_aspect":"OTHER","sub_aspect":"OTHER","sentiment":"neutral"}}
"ㅋㅋㅋㅋㅋ" → {{"top_aspect":"OTHER","sub_aspect":"OTHER","sentiment":"neutral"}}

[기타]
"그래픽 예쁨" → {{"top_aspect":"AUDIOVISUAL","sub_aspect":"AV_GRAPHICS","sentiment":"positive"}}
"핵쟁이 많음" → {{"top_aspect":"MULTI_COMMUNITY","sub_aspect":"MULTI_FAIRNESS","sentiment":"negative"}}
"DLC 비쌈" → {{"top_aspect":"ECONOMY_PROGRESSION","sub_aspect":"ECO_MONETIZATION","sentiment":"negative"}}
"난이도 적당" → {{"top_aspect":"SYSTEM_BALANCE","sub_aspect":"SYS_DIFFICULTY","sentiment":"positive"}}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
출력 형식 (필수)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[{{"top_aspect":"GAMEPLAY","sub_aspect":"GP_FUN","sentiment":"positive"}},{{"top_aspect":"TECHNICAL","sub_aspect":"TECH_BUG","sentiment":"negative"}}]

규칙:
- 순수 JSON 배열만 출력
- 마크다운(```) 사용 금지
- 추가 설명 금지
- 반드시 {len(sentences)}개 출력
- top과 sub는 반드시 매칭 (GAMEPLAY→GP_, TECHNICAL→TECH_)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
문장 목록 ({len(sentences)}개)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{sentences_text}

위 {len(sentences)}개 문장을 순서대로 라벨링하여 JSON 배열로만 출력하시오.
""".strip()

    for attempt in range(max_retry):
        try:
            if debug and attempt > 0:
                print(f"[RETRY] {attempt+1}번째 시도...")
                
            resp = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=8000
            )
            
            content = resp.choices[0].message.content.strip()
            
            # 마크다운 제거
            if content.startswith("```"):
                lines = content.split("\n")
                content = "\n".join([l for l in lines if not l.strip().startswith("```")])
                content = content.strip()
            
            if debug:
                print(f"[Response Length] {len(content)} chars")
                usage = resp.usage
                print(f"[Tokens] Input: {usage.prompt_tokens}, Output: {usage.completion_tokens}/{8000}")
                print(f"[Finish] {resp.choices[0].finish_reason}")
            
            result = json.loads(content)
            
            # 개수 검증
            if len(result) != len(sentences):
                print(f"⚠️ 문장 수 불일치: 입력 {len(sentences)} vs 출력 {len(result)}")
                
                if len(result) > len(sentences):
                    result = result[:len(sentences)]
                    print(f"   → 초과분 제거")
                elif attempt < max_retry - 1:
                    time.sleep(1)
                    continue
                else:
                    missing = len(sentences) - len(result)
                    print(f"   → {missing}개 부족, OTHER로 채움")
                    for _ in range(missing):
                        result.append({"top_aspect": "OTHER", "sub_aspect": "OTHER", "sentiment": "neutral"})
            
            # 필수 키 검증
            for i, r in enumerate(result):
                if not r.get('top_aspect'):
                    r['top_aspect'] = 'OTHER'
                if not r.get('sub_aspect'):
                    r['sub_aspect'] = 'OTHER'
                if not r.get('sentiment'):
                    r['sentiment'] = 'neutral'
            
            if debug:
                print(f"✓ JSON 파싱 성공: {len(result)}개 라벨")
            
            return result
        
        except json.JSONDecodeError as e:
            print(f"❌ JSON Error (retry {attempt+1}/{max_retry}): {str(e)[:100]}")
            time.sleep(1)
            
        except Exception as e:
            print(f"❌ API Error: {type(e).__name__}")
            time.sleep(2)

    print(f"🔴 [FALLBACK] {len(sentences)}개 → OTHER")
    return [{"top_aspect": "OTHER", "sub_aspect": "OTHER", "sentiment": "neutral"} for _ in sentences]

In [ ]:
BATCH_SIZE = 20  # 🔧 테스트 결과 기반으로 20으로 고정
OUTPUT_PATH = "annotated_sampled.csv"

base_df = df_sent_sampled  
sent_list = base_df["sentence"].tolist()
app_list = base_df["app_id"].tolist()
genre_list = base_df["primary_genre"].tolist()

# 이미 처리된 부분 확인
if os.path.exists(OUTPUT_PATH):
    df_done = pd.read_csv(OUTPUT_PATH)
    processed = len(df_done)
    print(f"이미 처리된 문장 수: {processed}")
else:
    df_done = pd.DataFrame()
    processed = 0
    print("기존 결과 없음. 새로 시작합니다.")

total = len(sent_list)
print(f"총 라벨링 대상 문장 수: {total}")
print(f"BATCH_SIZE: {BATCH_SIZE}")
print(f"예상 API 호출 횟수: {(total - processed) // BATCH_SIZE + 1}")
print("\n라벨링 시작...\n")

# 진행 상황 추적
checkpoint_interval = 10  # 10개 배치마다 상세 로그
other_ratios = []

for start in range(processed, total, BATCH_SIZE):
    end = min(start + BATCH_SIZE, total)
    batch_num = (start - processed) // BATCH_SIZE + 1

    batch_sentences = sent_list[start:end]
    batch_app = app_list[start:end]
    batch_genre = genre_list[start:end]

    # 체크포인트마다 디버그 모드
    is_checkpoint = (batch_num % checkpoint_interval == 0)
    
    batch_results = annotate_sentences_batch_fn(
        batch_sentences, 
        debug=is_checkpoint
    )

    # OTHER 비율 체크
    other_count = sum(1 for r in batch_results if r.get('top_aspect') == 'OTHER')
    other_ratio = other_count / len(batch_results) * 100
    other_ratios.append(other_ratio)
    
    batch_rows = []
    for s, app, genre, result in zip(batch_sentences, batch_app, batch_genre, batch_results):
        batch_rows.append({
            "app_id": app,
            "primary_genre": genre,
            "sentence": s,
            "top_aspect": result.get("top_aspect"),
            "sub_aspect": result.get("sub_aspect"),
            "sentiment": result.get("sentiment"),
        })

    df_batch = pd.DataFrame(batch_rows)

    # CSV에 append
    import os
    header = not os.path.exists(OUTPUT_PATH) or (start == 0 and processed == 0)
    df_batch.to_csv(
        OUTPUT_PATH,
        mode="a",
        header=header,
        index=False,
        encoding="utf-8-sig"
    )

    # 상태 표시
    status = "⚠️" if other_ratio > 40 else "✓"
    progress = f"{end}/{total} ({end/total*100:.1f}%)"
    
    if is_checkpoint:
        avg_other = sum(other_ratios[-checkpoint_interval:]) / len(other_ratios[-checkpoint_interval:])
        print(f"{status} [{batch_num}] {progress} | OTHER: {other_count}/{len(batch_results)} ({other_ratio:.1f}%) | 최근 평균: {avg_other:.1f}%")
    else:
        print(f"{status} [{batch_num}] {progress} | OTHER: {other_count}/{len(batch_results)} ({other_ratio:.1f}%)")
    
    # API 호출 제한 방지
    time.sleep(0.5)

print("\n" + "="*60)
print("라벨링 완료!")
print("="*60)

# 최종 결과 확인
df_final = pd.read_csv(OUTPUT_PATH)
print(f"\n총 라벨링 문장 수: {len(df_final):,}")

print("\n=== top_aspect 분포 ===")
top_dist = df_final['top_aspect'].value_counts()
for aspect, count in top_dist.items():
    print(f"{aspect:25s}: {count:5d} ({count/len(df_final)*100:5.1f}%)")

print("\n=== sentiment 분포 ===")
sent_dist = df_final['sentiment'].value_counts()
for sentiment, count in sent_dist.items():
    print(f"{sentiment:10s}: {count:5d} ({count/len(df_final)*100:5.1f}%)")

print(f"\n전체 평균 OTHER 비율: {sum(other_ratios)/len(other_ratios):.1f}%")
print(f"저장 위치: {OUTPUT_PATH}")

기존 결과 없음. 새로 시작합니다.
총 라벨링 대상 문장 수: 12403
BATCH_SIZE: 20
예상 API 호출 횟수: 621

라벨링 시작...

⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [1] 20/12403 (0.2%) | OTHER: 2/20 (10.0%)
✓ [2] 40/12403 (0.3%) | OTHER: 7/20 (35.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [3] 60/12403 (0.5%) | OTHER: 1/20 (5.0%)
✓ [4] 80/12403 (0.6%) | OTHER: 3/20 (15.0%)
✓ [5] 100/12403 (0.8%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [6] 120/12403 (1.0%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [7] 140/12403 (1.1%) | OTHER: 2/20 (10.0%)
✓ [8] 160/12403 (1.3%) | OTHER: 7/20 (35.0%)
✓ [9] 180/12403 (1.5%) | OTHER: 2/20 (10.0%)
[Response Length] 1419 chars
[Tokens] Input: 2476, Output: 373/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
⚠️ [10] 200/12403 (1.6%) | OTHER: 9/20 (45.0%) | 최근 평균: 20.5%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [11] 220/12403 (1.8%) | OTHER: 2/20 (10.0%)
✓ [12] 240/12403 (1.9%) | OTHER: 1/20 (5.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [13] 260/12403 (2.1%) | OTHER: 5/20 (25.0%)
⚠️ [14] 280/12403 (2.3%) | OTHER: 10/20 (50.0%)
✓ [15] 300/12403 (2.4%) | OTHER: 7/20 (35.0%)
✓ [16] 320/12403 (2.6%) | OTHER: 6/20 (30.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [17] 340/12403 (2.7%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [18] 360/12403 (2.9%) | OTHER: 7/20 (35.0%)
✓ [19] 380/12403 (3.1%) | OTHER: 5/20 (25.0%)
[Response Length] 1536 chars
[Tokens] Input: 2670, Output: 409/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [20] 400/12403 (3.2%) | OTHER: 6/20 (30.0%) | 최근 평균: 26.5%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [21] 420/12403 (3.4%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [22] 440/12403 (3.5%) | OTHER: 5/20 (25.0%)
✓ [23] 460/12403 (3.7%) | OTHER: 4/20 (20.0%)
✓ [24] 480/12403 (3.9%) | OTHER: 6/20 (30.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [25] 500/12403 (4.0%) | OTHER: 1/20 (5.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [26] 520/12403 (4.2%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [27] 540/12403 (4.4%) | OTHER: 3/20 (15.0%)
✓ [28] 560/12403 (4.5%) | OTHER: 4/20 (20.0%)
⚠️ [29] 580/12403 (4.7%) | OTHER: 13/20 (65.0%)
[Response Length] 1514 chars
[Tokens] Input: 2587, Output: 405/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [30] 600/12403 (4.8%) | OTHER: 3/20 (15.0%) | 최근 평균: 22.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [31] 620/12403 (5.0%) | OTHER: 6/20 (30.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [32] 640/12403 (5.2%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [33] 660/12403 (5.3%) | OTHER: 8/20 (40.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [34] 680/12403 (5.5%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [35] 700/12403 (5.6%) | OTHER: 1/20 (5.0%)
⚠️ [36] 720/12403 (5.8%) | OTHER: 9/20 (45.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [37] 740/12403 (6.0%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [38] 760/12403 (6.1%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [39] 780/12403 (6.3%) | OTHER: 4/20 (20.0%)
[Response Length] 1535 chars
[Tokens] Input: 2913, Output: 400/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [40] 800/12403 (6.5%) | OTHER: 3/20 (15.0%) | 최근 평균: 21.5%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [41] 820/12403 (6.6%) | OTHER: 5/20 (25.0%)
✓ [42] 840/12403 (6.8%) | OTHER: 5/20 (25.0%)
✓ [43] 860/12403 (6.9%) | OTHER: 1/20 (5.0%)
✓ [44] 880/12403 (7.1%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [45] 900/12403 (7.3%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [46] 920/12403 (7.4%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [47] 940/12403 (7.6%) | OTHER: 9/20 (45.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [48] 960/12403 (7.7%) | OTHER: 9/20 (45.0%)
✓ [49] 980/12403 (7.9%) | OTHER: 7/20 (35.0%)
[Response Length] 1470 chars
[Tokens] Input: 2583, Output: 393/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [50] 1000/12403 (8.1%) | OTHER: 8/20 (40.0%) | 최근 평균: 27.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [51] 1020/12403 (8.2%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [52] 1040/12403 (8.4%) | OTHER: 9/20 (45.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [53] 1060/12403 (8.5%) | OTHER: 4/20 (20.0%)
✓ [54] 1080/12403 (8.7%) | OTHER: 2/20 (10.0%)
✓ [55] 1100/12403 (8.9%) | OTHER: 4/20 (20.0%)
✓ [56] 1120/12403 (9.0%) | OTHER: 2/20 (10.0%)
✓ [57] 1140/12403 (9.2%) | OTHER: 5/20 (25.0%)
✓ [58] 1160/12403 (9.4%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [59] 1180/12403 (9.5%) | OTHER: 6/20 (30.0%)
[Response Length] 1499 chars
[Tokens] Input: 2467, Output: 396/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [60] 1200/12403 (9.7%) | OTHER: 6/20 (30.0%) | 최근 평균: 23.5%
✓ [61] 1220/12403 (9.8%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [62] 1240/12403 (10.0%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [63] 1260/12403 (10.2%) | OTHER: 6/20 (30.0%)
✓ [64] 1280/12403 (10.3%) | OTHER: 2/20 (10.0%)
✓ [65] 1300/12403 (10.5%) | OTHER: 6/20 (30.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [66] 1320/12403 (10.6%) | OTHER: 7/20 (35.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 19
✓ [67] 1340/12403 (10.8%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [68] 1360/12403 (11.0%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [69] 1380/12403 (11.1%) | OTHER: 6/20 (30.0%)
[Response Length] 1463 chars
[Tokens] Input: 2803, Output: 391/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [70] 1400/12403 (11.3%) | OTHER: 2/20 (10.0%) | 최근 평균: 19.5%
✓ [71] 1420/12403 (11.4%) | OTHER: 6/20 (30.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [72] 1440/12403 (11.6%) | OTHER: 1/20 (5.0%)
✓ [73] 1460/12403 (11.8%) | OTHER: 6/20 (30.0%)
✓ [74] 1480/12403 (11.9%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [75] 1500/12403 (12.1%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [76] 1520/12403 (12.3%) | OTHER: 6/20 (30.0%)
✓ [77] 1540/12403 (12.4%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [78] 1560/12403 (12.6%) | OTHER: 3/20 (15.0%)
✓ [79] 1580/12403 (12.7%) | OTHER: 3/20 (15.0%)
[Response Length] 1492 chars
[Tokens] Input: 2590, Output: 395/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [80] 1600/12403 (12.9%) | OTHER: 3/20 (15.0%) | 최근 평균: 21.5%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [81] 1620/12403 (13.1%) | OTHER: 3/20 (15.0%)
⚠️ [82] 1640/12403 (13.2%) | OTHER: 10/20 (50.0%)
✓ [83] 1660/12403 (13.4%) | OTHER: 5/20 (25.0%)
✓ [84] 1680/12403 (13.5%) | OTHER: 5/20 (25.0%)
⚠️ [85] 1700/12403 (13.7%) | OTHER: 13/20 (65.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [86] 1720/12403 (13.9%) | OTHER: 7/20 (35.0%)
✓ [87] 1740/12403 (14.0%) | OTHER: 5/20 (25.0%)
✓ [88] 1760/12403 (14.2%) | OTHER: 3/20 (15.0%)
✓ [89] 1780/12403 (14.4%) | OTHER: 8/20 (40.0%)
[Response Length] 1468 chars
[Tokens] Input: 2690, Output: 386/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [90] 1800/12403 (14.5%) | OTHER: 6/20 (30.0%) | 최근 평균: 32.5%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [91] 1820/12403 (14.7%) | OTHER: 7/20 (35.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [92] 1840/12403 (14.8%) | OTHER: 1/20 (5.0%)
✓ [93] 1860/12403 (15.0%) | OTHER: 6/20 (30.0%)
✓ [94] 1880/12403 (15.2%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [95] 1900/12403 (15.3%) | OTHER: 9/20 (45.0%)
✓ [96] 1920/12403 (15.5%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [97] 1940/12403 (15.6%) | OTHER: 7/20 (35.0%)
✓ [98] 1960/12403 (15.8%) | OTHER: 1/20 (5.0%)
✓ [99] 1980/12403 (16.0%) | OTHER: 2/20 (10.0%)
[Response Length] 1448 chars
[Tokens] Input: 2630, Output: 387/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [100] 2000/12403 (16.1%) | OTHER: 7/20 (35.0%) | 최근 평균: 24.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [101] 2020/12403 (16.3%) | OTHER: 5/20 (25.0%)
✓ [102] 2040/12403 (16.4%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [103] 2060/12403 (16.6%) | OTHER: 3/20 (15.0%)
✓ [104] 2080/12403 (16.8%) | OTHER: 3/20 (15.0%)
✓ [105] 2100/12403 (16.9%) | OTHER: 6/20 (30.0%)
✓ [106] 2120/12403 (17.1%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [107] 2140/12403 (17.3%) | OTHER: 3/20 (15.0%)
✓ [108] 2160/12403 (17.4%) | OTHER: 5/20 (25.0%)
✓ [109] 2180/12403 (17.6%) | OTHER: 3/20 (15.0%)
[Response Length] 1426 chars
[Tokens] Input: 2756, Output: 373/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [110] 2200/12403 (17.7%) | OTHER: 7/20 (35.0%) | 최근 평균: 22.0%
✓ [111] 2220/12403 (17.9%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [112] 2240/12403 (18.1%) | OTHER: 8/20 (40.0%)
✓ [113] 2260/12403 (18.2%) | OTHER: 4/20 (20.0%)
✓ [114] 2280/12403 (18.4%) | OTHER: 6/20 (30.0%)
✓ [115] 2300/12403 (18.5%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [116] 2320/12403 (18.7%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [117] 2340/12403 (18.9%) | OTHER: 9/20 (45.0%)
✓ [118] 2360/12403 (19.0%) | OTHER: 5/20 (25.0%)
✓ [119] 2380/12403 (19.2%) | OTHER: 5/20 (25.0%)
[Response Length] 1445 chars
[Tokens] Input: 2566, Output: 384/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [120] 2400/12403 (19.4%) | OTHER: 2/20 (10.0%) | 최근 평균: 24.5%
✓ [121] 2420/12403 (19.5%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [122] 2440/12403 (19.7%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [123] 2460/12403 (19.8%) | OTHER: 9/20 (45.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [124] 2480/12403 (20.0%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 16
✓ [125] 2500/12403 (20.2%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [126] 2520/12403 (20.3%) | OTHER: 5/20 (25.0%)
✓ [127] 2540/12403 (20.5%) | OTHER: 7/20 (35.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [128] 2560/12403 (20.6%) | OTHER: 7/20 (35.0%)
✓ [129] 2580/12403 (20.8%) | OTHER: 2/20 (10.0%)
[Response Length] 1581 chars
[Tokens] Input: 2574, Output: 416/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [130] 2600/12403 (21.0%) | OTHER: 3/20 (15.0%) | 최근 평균: 22.5%
✓ [131] 2620/12403 (21.1%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [132] 2640/12403 (21.3%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [133] 2660/12403 (21.4%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [134] 2680/12403 (21.6%) | OTHER: 9/20 (45.0%)
✓ [135] 2700/12403 (21.8%) | OTHER: 6/20 (30.0%)
✓ [136] 2720/12403 (21.9%) | OTHER: 1/20 (5.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [137] 2740/12403 (22.1%) | OTHER: 6/20 (30.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [138] 2760/12403 (22.3%) | OTHER: 8/20 (40.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [139] 2780/12403 (22.4%) | OTHER: 5/20 (25.0%)
[Response Length] 1577 chars
[Tokens] Input: 2589, Output: 418/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [140] 2800/12403 (22.6%) | OTHER: 2/20 (10.0%) | 최근 평균: 24.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [141] 2820/12403 (22.7%) | OTHER: 6/20 (30.0%)
✓ [142] 2840/12403 (22.9%) | OTHER: 6/20 (30.0%)
✓ [143] 2860/12403 (23.1%) | OTHER: 3/20 (15.0%)
✓ [144] 2880/12403 (23.2%) | OTHER: 0/20 (0.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [145] 2900/12403 (23.4%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [146] 2920/12403 (23.5%) | OTHER: 3/20 (15.0%)
✓ [147] 2940/12403 (23.7%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [148] 2960/12403 (23.9%) | OTHER: 9/20 (45.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [149] 2980/12403 (24.0%) | OTHER: 8/20 (40.0%)
[Response Length] 1588 chars
[Tokens] Input: 2591, Output: 432/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [150] 3000/12403 (24.2%) | OTHER: 2/20 (10.0%) | 최근 평균: 22.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [151] 3020/12403 (24.3%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [152] 3040/12403 (24.5%) | OTHER: 5/20 (25.0%)
✓ [153] 3060/12403 (24.7%) | OTHER: 0/20 (0.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [154] 3080/12403 (24.8%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [155] 3100/12403 (25.0%) | OTHER: 3/20 (15.0%)
✓ [156] 3120/12403 (25.2%) | OTHER: 5/20 (25.0%)
✓ [157] 3140/12403 (25.3%) | OTHER: 5/20 (25.0%)
✓ [158] 3160/12403 (25.5%) | OTHER: 8/20 (40.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [159] 3180/12403 (25.6%) | OTHER: 8/20 (40.0%)
[Response Length] 1508 chars
[Tokens] Input: 2634, Output: 399/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [160] 3200/12403 (25.8%) | OTHER: 7/20 (35.0%) | 최근 평균: 24.0%
✓ [161] 3220/12403 (26.0%) | OTHER: 1/20 (5.0%)
✓ [162] 3240/12403 (26.1%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [163] 3260/12403 (26.3%) | OTHER: 3/20 (15.0%)
✓ [164] 3280/12403 (26.4%) | OTHER: 4/20 (20.0%)
✓ [165] 3300/12403 (26.6%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [166] 3320/12403 (26.8%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [167] 3340/12403 (26.9%) | OTHER: 3/20 (15.0%)
✓ [168] 3360/12403 (27.1%) | OTHER: 4/20 (20.0%)
✓ [169] 3380/12403 (27.3%) | OTHER: 3/20 (15.0%)
[Response Length] 1600 chars
[Tokens] Input: 2754, Output: 438/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [170] 3400/12403 (27.4%) | OTHER: 2/20 (10.0%) | 최근 평균: 15.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [171] 3420/12403 (27.6%) | OTHER: 5/20 (25.0%)
✓ [172] 3440/12403 (27.7%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [173] 3460/12403 (27.9%) | OTHER: 5/20 (25.0%)
✓ [174] 3480/12403 (28.1%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [175] 3500/12403 (28.2%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [176] 3520/12403 (28.4%) | OTHER: 3/20 (15.0%)
✓ [177] 3540/12403 (28.5%) | OTHER: 6/20 (30.0%)
✓ [178] 3560/12403 (28.7%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [179] 3580/12403 (28.9%) | OTHER: 1/20 (5.0%)
[Response Length] 1487 chars
[Tokens] Input: 2629, Output: 403/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [180] 3600/12403 (29.0%) | OTHER: 1/20 (5.0%) | 최근 평균: 17.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [181] 3620/12403 (29.2%) | OTHER: 9/20 (45.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [182] 3640/12403 (29.3%) | OTHER: 8/20 (40.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [183] 3660/12403 (29.5%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [184] 3680/12403 (29.7%) | OTHER: 3/20 (15.0%)
✓ [185] 3700/12403 (29.8%) | OTHER: 6/20 (30.0%)
✓ [186] 3720/12403 (30.0%) | OTHER: 2/20 (10.0%)
✓ [187] 3740/12403 (30.2%) | OTHER: 8/20 (40.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [188] 3760/12403 (30.3%) | OTHER: 4/20 (20.0%)
✓ [189] 3780/12403 (30.5%) | OTHER: 5/20 (25.0%)
[Response Length] 1527 chars
[Tokens] Input: 2537, Output: 409/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [190] 3800/12403 (30.6%) | OTHER: 5/20 (25.0%) | 최근 평균: 26.0%
✓ [191] 3820/12403 (30.8%) | OTHER: 3/20 (15.0%)
✓ [192] 3840/12403 (31.0%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [193] 3860/12403 (31.1%) | OTHER: 7/20 (35.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [194] 3880/12403 (31.3%) | OTHER: 1/20 (5.0%)
✓ [195] 3900/12403 (31.4%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [196] 3920/12403 (31.6%) | OTHER: 10/20 (50.0%)
✓ [197] 3940/12403 (31.8%) | OTHER: 3/20 (15.0%)
✓ [198] 3960/12403 (31.9%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [199] 3980/12403 (32.1%) | OTHER: 5/20 (25.0%)
[Response Length] 1457 chars
[Tokens] Input: 2606, Output: 394/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [200] 4000/12403 (32.3%) | OTHER: 4/20 (20.0%) | 최근 평균: 22.0%
✓ [201] 4020/12403 (32.4%) | OTHER: 2/20 (10.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [202] 4040/12403 (32.6%) | OTHER: 3/20 (15.0%)
✓ [203] 4060/12403 (32.7%) | OTHER: 1/20 (5.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [204] 4080/12403 (32.9%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [205] 4100/12403 (33.1%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [206] 4120/12403 (33.2%) | OTHER: 7/20 (35.0%)
✓ [207] 4140/12403 (33.4%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [208] 4160/12403 (33.5%) | OTHER: 4/20 (20.0%)
✓ [209] 4180/12403 (33.7%) | OTHER: 6/20 (30.0%)
[Response Length] 1506 chars
[Tokens] Input: 2780, Output: 411/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [210] 4200/12403 (33.9%) | OTHER: 1/20 (5.0%) | 최근 평균: 18.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [211] 4220/12403 (34.0%) | OTHER: 4/20 (20.0%)
✓ [212] 4240/12403 (34.2%) | OTHER: 7/20 (35.0%)
✓ [213] 4260/12403 (34.3%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [214] 4280/12403 (34.5%) | OTHER: 3/20 (15.0%)
✓ [215] 4300/12403 (34.7%) | OTHER: 4/20 (20.0%)
✓ [216] 4320/12403 (34.8%) | OTHER: 5/20 (25.0%)
✓ [217] 4340/12403 (35.0%) | OTHER: 1/20 (5.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [218] 4360/12403 (35.2%) | OTHER: 1/20 (5.0%)
✓ [219] 4380/12403 (35.3%) | OTHER: 5/20 (25.0%)
[Response Length] 1494 chars
[Tokens] Input: 2560, Output: 405/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [220] 4400/12403 (35.5%) | OTHER: 6/20 (30.0%) | 최근 평균: 20.0%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [221] 4420/12403 (35.6%) | OTHER: 2/20 (10.0%)
✓ [222] 4440/12403 (35.8%) | OTHER: 5/20 (25.0%)
✓ [223] 4460/12403 (36.0%) | OTHER: 1/20 (5.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [224] 4480/12403 (36.1%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [225] 4500/12403 (36.3%) | OTHER: 7/20 (35.0%)
✓ [226] 4520/12403 (36.4%) | OTHER: 3/20 (15.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [227] 4540/12403 (36.6%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [228] 4560/12403 (36.8%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [229] 4580/12403 (36.9%) | OTHER: 5/20 (25.0%)
[Response Length] 1568 chars
[Tokens] Input: 2601, Output: 420/8000
[Finish] stop
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ JSON 파싱 성공: 20개 라벨
✓ [230] 4600/12403 (37.1%) | OTHER: 4/20 (20.0%) | 최근 평균: 20.5%
✓ [231] 4620/12403 (37.2%) | OTHER: 7/20 (35.0%)
✓ [232] 4640/12403 (37.4%) | OTHER: 4/20 (20.0%)
✓ [233] 4660/12403 (37.6%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [234] 4680/12403 (37.7%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
⚠️ [235] 4700/12403 (37.9%) | OTHER: 11/20 (55.0%)
✓ [236] 4720/12403 (38.1%) | OTHER: 2/20 (10.0%)
✓ [237] 4740/12403 (38.2%) | OTHER: 5/20 (25.0%)
✓ [238] 4760/12403 (38.4%) | OTHER: 4/20 (20.0%)
✓ [239] 4780/12403 (38.5%) | OTHER: 6/20 (30.0%)
[Response Length] 1453 chars
[Tokens] Input: 2631, Output: 385/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [240] 4800/12403 (38.7%) | OTHER: 4/20 (20.0%) | 최근 평균: 26.0%
✓ [241] 4820/12403 (38.9%) | OTHER: 2/20 (10.0%)
✓ [242] 4840/12403 (39.0%) | OTHER: 4/20 (20.0%)
✓ [243] 4860/12403 (39.2%) | OTHER: 5/20 (25.0%)
✓ [244] 4880/12403 (39.3%) | OTHER: 2/20 (10.0%)
✓ [245] 4900/12403 (39.5%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [246] 4920/12403 (39.7%) | OTHER: 6/20 (30.0%)
✓ [247] 4940/12403 (39.8%) | OTHER: 5/20 (25.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [248] 4960/12403 (40.0%) | OTHER: 4/20 (20.0%)
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [249] 4980/12403 (40.2%) | OTHER: 3/20 (15.0%)
[Response Length] 1527 chars
[Tokens] Input: 2704, Output: 409/8000
[Finish] stop
✓ JSON 파싱 성공: 20개 라벨
✓ [250] 5000/12403 (40.3%) | OTHER: 2/20 (10.0%) | 최근 평균: 18.5%
⚠️ 문장 수 불일치: 입력 20 vs 출력 21
   → 초과분 제거
✓ [251] 5020/12403 (40.5%) | OTHER: 4/20 (20.0%)

In [80]:
original_count = len(df_final)

# 1. top-sub 혼동 수정

corrections = {
    'MULTI_FAIRNESS': 'MULTI_COMMUNITY',    # 핵/공정성
    'MULTI_MATCHING': 'MULTI_COMMUNITY',    # 매칭
    'MULTI_SOCIAL': 'MULTI_COMMUNITY',      # 협동/소통
    'TECH_BUG': 'TECHNICAL',                # 버그
    'TECH_NET': 'TECHNICAL',                # 네트워크
    'ECO_MONETIZATION': 'ECONOMY_PROGRESSION',  # 과금
    'ECO_PROGRESSION': 'ECONOMY_PROGRESSION',   # 성장
    'AV_SOUND': 'AUDIOVISUAL',              # 사운드
}

for wrong_top, correct_top in corrections.items():
    mask = df_final['top_aspect'] == wrong_top
    count = mask.sum()
    if count > 0:
        # top 수정 (원래 top을 sub로 이동)
        df_final.loc[mask, 'sub_aspect'] = df_final.loc[mask, 'top_aspect']
        df_final.loc[mask, 'top_aspect'] = correct_top
        print(f"✓ {wrong_top} → {correct_top}: {count}개 수정")

✓ MULTI_FAIRNESS → MULTI_COMMUNITY: 5개 수정
✓ MULTI_MATCHING → MULTI_COMMUNITY: 2개 수정
✓ MULTI_SOCIAL → MULTI_COMMUNITY: 1개 수정
✓ TECH_BUG → TECHNICAL: 2개 수정
✓ TECH_NET → TECHNICAL: 1개 수정
✓ ECO_MONETIZATION → ECONOMY_PROGRESSION: 1개 수정
✓ ECO_PROGRESSION → ECONOMY_PROGRESSION: 2개 수정
✓ AV_SOUND → AUDIOVISUAL: 1개 수정

In [82]:
df_final['top_aspect'].unique()

array(['GAMEPLAY', 'OTHER', 'AUDIOVISUAL', 'TECHNICAL',
       'ECONOMY_PROGRESSION', 'MULTI_COMMUNITY', 'SYSTEM_BALANCE'],
      dtype=object)

In [83]:
df_final.to_csv('annotated_sampled_fn.csv')